spring:
    profiles:
        active: dev
    flyway:
        enabled: true
        baselineOnMigrate: true
        validateOnMigrate: false
    datasource:
        url: jdbc:mysql://localhost:3306/stationary_inventory
        username: kkpuser
        password: kkppassword1
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:  
            ddl-auto: create-drop          
        show-sql: true
        properties:
            hibernate:
                format-sql: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQLDialect

logging:
  level:
    '[com.project.dex]': DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"