spring:
    datasource:
        url: jdbc:mysql://localhost:3306/stationary?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&autoReconnect=true&useSSL=false&noAccessToProcedureBodies=true
        username: root
        password: 
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            connectionTimeout: 30000
            idleTimeout: 600000 
            maxLifetime: 1800000
            maximumPoolSize: 200
    jpa:
        hibernate:  
            ddl-auto: update 
        show-sql: true
        properties:
            hibernate:
                format-sql: true
                jdbc:
                    timeZone: UTC+1
                dialect: org.hibernate.dialect.MySQLDialect
                id:
                    newGeneratorMappings: false
                showSql: true
                formatSql: false
                nonContextualCreation: true
        database: mysql
        database-platform: org.hibernate.dialect.MySQL8Dialect